### ISSUE TITLE
Simplest metrics with Prometheus as a datasource

### ISSUE THREAD

**Issue by ivan-bezyazychnyy** [yoomoney/grafana-dashboard-dsl#7]
Hi! I am trying to generate a JSON dashboard for Grafana with Prometheus as a datasource. I created a metric in DSL:
`
metric("A") {
    StringMetric("task_age_seconds")
}
`
And in the generated json I see:
`
      "targets": [
        {
          "hide": false,
          "refId": "A",
          "target": "task_age_seconds"
        }
      ],
`
But Grafana does not show a graph on a panel for this JSON. As I understand, it expects `expr` field. I added the expression manually and got a graph for this JSON:
`
 "targets": [
        {
          "expr": "task_age_seconds",
          "hide": false,
          "refId": "A",
          "target": "task_age_seconds"
        }
      ],
`
Do I understand correctly that the JSON generated by this library is not intended to work with Prometheus as a datasource?

**Comment by komarovd95** [comment]
Hi there. There is no support for Prometheus as a datasource. Prometheus is very mature and popular as timeseries datastore, therefore, it could be nice idea to maintain different datasources in that library.

I am not maintainer of this library anymore. But I can propose some functionality to maintain Prometheus in the near future.

**Comment by f0y** [comment]
Fixed in the latest dsl version
